apiVersion: v1
kind: Service
metadata:
  name: k8s-lab-service
spec:
  selector:
    app: k8s-lab
  ports:
    - port: 80
      # reference to the named port from the Deployment, not a number
      targetPort: http
